# Generated by Django 2.1.7 on 2019-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(blank=True, max_length=50, null=True)),
                ('goods_category', models.CharField(blank=True, max_length=20, null=True)),
                ('goods_price', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('goods_summary', models.CharField(blank=True, max_length=200, null=True)),
                ('goods_detail', models.TextField()),
                ('create_name', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
    ]
